<!DOCTYPE html>
<html lang="id">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Feedback Management - Smart AOI Dashboard</title>
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="css/feedback.css">
    <link rel="stylesheet" href="css/notiflix.css">
</head>

<body>
    <header class="header-ui">
        <div class="header-info">
            <h1 class="header-title">FEEDBACK MANAGEMENT</h1>
            <p class="header-subtitle">Operator & Machine Result Verification</p>
        </div>
        <div class="header-clock-area">
            <a href="index.php" class="btn-report" style="background: var(--gray-color); color: var(--text-color);">
                <span class="report-icon">🏠</span> DASHBOARD
            </a>
            <a href="report.php" class="btn-report">
                <span class="report-icon">📊</span> KPI REPORT
            </a>
            <a href="feedback.php" class="btn-report" style="background: linear-gradient(90deg, var(--yellow-color), #f59e0b); color: var(--text-dark);">
                <span class="report-icon">🔍</span> FEEDBACK
            </a>
            <a href="summary_report.php" class="btn-report" style="background: linear-gradient(90deg, var(--green-color), #22c55e); color: var(--text-dark);">
                <span class="report-icon">📋</span> SUMMARY
            </a>
            <div class="header-clock">
                <p id="clock">00:00:00</p>
                <p id="date">Jumat, 10 Oktober 2025</p>
            </div>
        </div>
    </header>

    <main class="feedback-page-layout">
        <div class="card-ui feedback-list-panel">
            <div class="list-header">
                <h2>Verification Queue</h2>
                <p>Items requiring analyst review.</p>
                <form action="#" method="get" id="search-form">
                    <div class="filter-control">
                        <label for="search-input">Cari Assembly</label>
                        <input type="text" id="search-input" name="search-input" placeholder="Cari Assembly..." title="Cari Assembly">
                    </div>
                    <div style="align-self: flex-end;">
                        <button id="filter-btn" class="btn-filter">Cari</button>
                    </div>
                </form>
                <!-- PENAMBAHAN: Filter Controls -->
                <div class="list-filters">
                    <div class="filter-control">
                        <label for="line-filter">Line</label>
                        <select id="line-filter">
                            <option value="">All Lines</option>
                        </select>
                    </div>
                    <div class="filter-control">
                        <label for="defect-filter">Defect</label>
                        <select id="defect-filter">
                            <option value="">All Defects</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="table-container">
                <table id="feedback-table">
                    <thead>
                        <tr>
                            <!-- PENAMBAHAN: Kolom No. -->
                            <th>No.</th>
                            <th>Time</th>
                            <th>Line</th>
                            <th>Defect</th>
                            <th>Operator Result</th>
                        </tr>
                    </thead>
                    <tbody id="feedback-table-body">
                        <!-- Rows will be generated by JavaScript -->
                    </tbody>
                </table>
                <div id="loading-indicator">
                    <div class="spinner"></div>
                    <span>Loading Verification Data...</span>
                </div>
            </div>
        </div>

        <div class="card-ui feedback-detail-panel">
            <div id="detail-view-placeholder" class="placeholder-view">
                <svg xmlns="http://www.w3.org/2000/svg" width="80" height="80" fill="currentColor" class="bi bi-card-checklist" viewBox="0 0 16 16">
                    <path d="M14.5 3a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h13zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13z" />
                    <path d="M7 5.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5zm-1.496-.854a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.708 0l-.5-.5a.5.5 0 1 1 .708-.708l.146.147 1.146-1.147a.5.5 0 0 1 .708 0zM7 9.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5zm-1.496-.854a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.708 0l-.5-.5a.5.5 0 0 1 .708-.708l.146.147 1.146-1.147a.5.5 0 0 1 .708 0z" />
                </svg>
                <h3>Select an item to view details</h3>
                <p>Choose an inspection from the queue on the left to begin verification.</p>
            </div>
            <div id="detail-view-content" class="hidden">
                <!-- Detail content will be generated here -->
            </div>
        </div>
    </main>

    <script src="js/feedback.js"></script>
    <script src="js/notiflix.js"></script>

</body>

</html>